### ISSUE TITLE
Feature Request: TSelectDirectoryDialog

### ISSUE THREAD

**Issue by sherbakovAE** [ying32/govcl#13]
Thanks for the great job.
res2go displays a message: Warning: "DlgSelectFolder:TSelectDirectoryDialog" is not supported and it may fail to create. 
Possible to add TSelectDirectoryDialogto this binding?

**Comment by ying32** [comment]
Hi!
 
I found this to be an LCL component. Because there is no such VCL component, it cannot be added temporarily. However, you can replace this component with two API interfaces, "SelectDirectory1" or "SelectDirectory2". Detailed reference: [sysdialog](https://github.com/ying32/govcl/tree/master/samples/sysdialog) example.
