### ISSUE TITLE
什么时候能够开放mac 11.+版本

### ISSUE THREAD

**Issue by 17335736197** [ying32/govcl#75]
如题如题如题

**Comment by ying32** [comment]
你测试不能运行？liblcl跟govcl都是向下兼容的，如果你是指的macOS的ARM版那个我无能力为了。。。

**Comment by 17335736197** [comment]
我指的是mac系统版本- - 我的是11.2 然后不能运行

**Comment by ying32** [comment]
暂没听说有人运行不了的，你也没给出个具体错误信息来。。。

**Comment by lunny** [comment]
macOS 11.2.2，编译能成功，运行无反应

**Comment by ying32** [comment]
具体要看报什么错了，我也没得11.2.2的系统可以测试

**Comment by suifengqjn** [comment]
big sur 11.2.3 (20D91) 运行正常

**Comment by fesiong** [comment]
ld: warning: object file (/var/folders/l_/5pq2d7cs7s93bzg2fx5by6qw0000gn/T/go-link-1030049701/000012.o) was built for newer macOS version (11.3) than being linked (10.8)

**Comment by fesiong** [comment]
只是warning，之所以看不到界面，原因是：Why does my program start in the background on OS X if I run from the command line?
OS X normally does not start program executables directly; instead, it uses Launch Services to coordinate the launching of the program between the various parts of the system and the loading of info from an .app bundle. One of these coordination tasks is responsible for bringing a newly launched app into the foreground. This is called "activation".

When you run a binary directly from the Terminal, however, you are running it directly, not through Launch Services. Therefore, the program starts in the background, because no one told it to activate! Now, it turns out there is an API that we can use to force our app to be activated. But if we use it, then we'd be trampling over Launch Services, which already knows whether it should activate or not. Therefore, libui does not step over Launch Services, at the cost of requiring an extra user step if running directly from the command line.
